FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.26@sha256:c1488dc4364e229cb6963b4e0b088e3e93ef377bf92463d68b7b7e2ab1166f8f as image-replacer
COPY bundle/manifests /manifests
RUN sed -i "s|REPLACE_IMAGE|registry.redhat.io/openshift4-wincw/windows-machine-config-rhel9-operator@sha256:e499781bee625815bdaf88ed00ebdc397bf8ea8a4495dda1002d86d19072cae0|g" /manifests/windows-machine-config-operator.clusterserviceversion.yaml
RUN sed -i "s|REPLACE_DATE|$(date "+%Y-%m-%dT%H:%M:%SZ")|g" /manifests/windows-machine-config-operator.clusterserviceversion.yaml

FROM scratch

# This block contains standard Red Hat container labels
LABEL name="openshift4-wincw/windows-machine-config-operator-bundle" \
    License="ASL 2.0" \
    io.k8s.display-name="Windows Machine Config Operator bundle" \
    io.k8s.description="Windows Machine Config Operator's OLM bundle image" \
	description="Windows Machine Config Operator's OLM bundle image" \
    summary="Windows Machine Config Operator's OLM bundle image" \
    maintainer="Team Windows Containers <team-winc@redhat.com>" \
    io.openshift.tags=""

# Used to tag the released image. Should be a semver.
LABEL version="v11.0.0"
# Component to file bugs against
LABEL com.redhat.component="Windows Containers"
LABEL cpe="cpe:/a:redhat:windows_machine_config:11.0::el9"

# Core bundle labels.
LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=windows-machine-config-operator
LABEL operators.operatorframework.io.bundle.channels.v1=preview,stable
LABEL operators.operatorframework.io.bundle.channel.default.v1=stable
LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.32.0
LABEL operators.operatorframework.io.metrics.mediatype.v1=metrics+v1
LABEL operators.operatorframework.io.metrics.project_layout=go.kubebuilder.io/v3

LABEL distribution-scope=public
LABEL release="11.0.0"
LABEL url="https://docs.redhat.com/en/documentation/openshift_container_platform/5.0/html/windows_container_support_for_openshift/index"
LABEL vendor="Red Hat, Inc."
LABEL com.redhat.openshift.versions="=v5.0"

# create licenses directory
# See https://docs.redhat.com/en/documentation/red_hat_software_certification/2025/html-single/red_hat_openshift_software_certification_policy_guide/index#con-image-content-requirements_openshift-sw-cert-policy-container-images
COPY LICENSE /licenses/

# Copy files to locations specified by labels.
COPY --from=image-replacer /manifests /manifests/
COPY bundle/metadata /metadata/
