apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: windows-machine-config-operator
    app.kubernetes.io/part-of: wicd
  name: windows-instance-config-daemon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: windows-instance-config-daemon
subjects:
- kind: ServiceAccount
  name: windows-instance-config-daemon
  namespace: openshift-windows-machine-config-operator
